import { BarChart3Icon, EyeIcon, FileSearchIcon, GlobeIcon, ShieldIcon, TargetIcon, TrendingUpIcon, ZapIcon } from "lucide-react";
 
export const homeFeaturesData = [
    {
        icon: <BarChart3Icon size={28} />,
        title: "SEO Score",
        desc: "Get a comprehensive SEO score analyzing 50+ ranking factors with AI-powered insights.",
    },
    {
        icon: <ZapIcon size={28} />,
        title: "Performance",
        desc: "Analyze load times, page size, and Core Web Vitals to maximize your site speed.",
    },
    {
        icon: <ShieldIcon size={28} />,
        title: "Best Practices",
        desc: "Check meta tags, heading structure, image optimization, and technical SEO health.",
    },
    {
        icon: <EyeIcon size={28} />,
        title: "Accessibility",
        desc: "Ensure your site is accessible to all users with alt text, ARIA, and contrast checks.",
    },
    {
        icon: <TargetIcon size={28} />,
        title: "Keyword Analysis",
        desc: "Discover top keywords, density analysis, and content optimization opportunities.",
    },
    {
        icon: <TrendingUpIcon size={28} />,
        title: "Actionable Fixes",
        desc: "Get prioritized, actionable recommendations to boost your search rankings.",
    },
];
 
export const homeHowItWorksData = [
    {
        num: "01",
        icon: <GlobeIcon size={24} />,
        title: "Enter Your URL",
        desc: "Paste any website URL into the analyzer bar.",
    },
    {
        num: "02",
        icon: <FileSearchIcon size={24} />,
        title: "AI Scans Your Site",
        desc: "Our engine visits your site and Gemini AI analyzes every SEO factor.",
    },
    {
        num: "03",
        icon: <BarChart3Icon size={24} />,
        title: "Get Your Report",
        desc: "Receive a detailed report with scores, issues, and recommendations.",
    },
];
 
export const homefooterLinks = [
    {
        title: "Product",
        links: ["Features", "Pricing", "API", "Browser Extension"],
    },
    {
        title: "Resources",
        links: ["Documentation", "Blog", "SEO Guide", "Support"],
    },
    {
        title: "Company",
        links: ["About Us", "Careers", "Contact", "Press"],
    },
    {
        title: "Legal",
        links: ["Privacy Policy", "Terms of Service", "Cookie Policy"],
    },
];
 
export const HomeWave = () => (
    <svg className="w-full h-[15vh] min-h-[60px] max-h-[120px]" xmlns="http://www.w3.org/2000/svg" xmlnsXlink="http://www.w3.org/1999/xlink" viewBox="0 24 150 28" preserveAspectRatio="none" shapeRendering="auto">
        <defs>
            <path id="gentle-wave" d="M-160 44c30 0 58-18 88-18s 58 18 88 18 58-18 88-18 58 18 88 18 v44h-352z" />
        </defs>
        <g className="parallax">
            <use xlinkHref="#gentle-wave" x="48" y="0" fill="var(--accent)" opacity="0.05" />
            <use xlinkHref="#gentle-wave" x="48" y="3" fill="var(--accent)" opacity="0.1" />
            <use xlinkHref="#gentle-wave" x="48" y="5" fill="var(--accent)" opacity="0.15" />
            <use xlinkHref="#gentle-wave" x="48" y="7" fill="var(--accent)" opacity="0.2" />
        </g>
    </svg>
);
 
export const dummyAnalysisData = [
    {
        categories: { seo: 65, performance: 50, accessibility: 85, bestPractices: 70 },
        metaData: {
            title: "Online Shopping site in India: Shop Online for Mobiles, Books, Watches, Shoes and More - Amazon.in",
            description: "Amazon.in: Online Shopping India - Buy mobiles, laptops, cameras, books, watches, apparel, shoes and e-Gift Cards. Free Shipping & Cash on Delivery Available.",
            canonical: "https://www.amazon.in/",
            robots: "",
            ogTitle: "",
            ogDescription: "Amazon.in: Online Shopping India - Buy mobiles, laptops, cameras, books, watches, apparel, shoes and e-Gift Cards. Free Shipping & Cash on Delivery Available.",
            ogImage: "https://m.media-amazon.com/images/I/51HCHFclmmL.jpg",
            twitterCard: "",
            viewport: "",
            charset: "utf-8",
        },
        headings: { h1: 0, h2: 25, h3: 0, h4: 0, h5: 7, h6: 0, h1Texts: [] },
        links: { broken: 0, internal: 350, external: 25, total: 375 },
        images: { total: 229, missingAlt: 10, withAlt: 219 },
        _id: "69fafd289a3aab480dd24147",
        userId: "69dcf7cacc98f8daf29ecca3",
        url: "https://amazon.in/",
        overallScore: 72,
        loadTime: 5032,
        pageSize: 1163453,
        wordCount: 2132,
        status: "completed",
        createdAt: "2026-05-06T08:34:48.581Z",
        updatedAt: "2026-05-06T08:35:24.611Z",
    },
    {
        categories: { seo: 65, performance: 55, accessibility: 60, bestPractices: 80 },
        metaData: {
            twitterCard: "",
            viewport: "",
            charset: "",
            title: "eBay - Export from India | Become a global online seller",
            description: "eBay is a leading global selling platform for online sellers to export products from India and sell globally. Start your global selling journey with eBay today! Low set-up cost | High profitability",
            canonical: "https://export.ebay.com/in/",
            robots: "",
            ogTitle: "eBay - Export from India | Become a global online seller",
            ogDescription: "eBay is a leading global selling platform for online sellers to export products from India and sell globally. Start your global selling journey with eBay today! Low set-up cost | High profitability",
            ogImage: "/_next/static/images/og-image-ebay-9997ef0e03c45b550a3e445b411aa3c7.png",
        },
        headings: { h4: 0, h5: 0, h6: 0, h1: 0, h2: 33, h3: 3, h1Texts: [] },
        links: { broken: 0, total: 0, internal: 131, external: 20 },
        images: { withAlt: 0, total: 26, missingAlt: 6 },
        _id: "69faf680e608e8071d2bd73f",
        userId: "69dcf7cacc98f8daf29ecca3",
        url: "https://ebay.in/",
        overallScore: 72,
        loadTime: 4936,
        pageSize: 352368,
        wordCount: 1191,
        status: "completed",
        createdAt: "2026-05-06T08:06:24.382Z",
        updatedAt: "2026-05-06T08:06:50.481Z",
    },
    {
        categories: { seo: 85, performance: 75, accessibility: 70, bestPractices: 80 },
        metaData: {
            title: "Microsoft – AI, Cloud, Productivity, Computing, Gaming & Apps",
            description: "Explore Microsoft products and services and support for your home or business. Shop Microsoft 365, Copilot, Teams, Xbox, Windows, Azure, Surface and more.",
            canonical: "https://www.microsoft.com/en-us",
            robots: "index, follow",
            ogTitle: "Microsoft – AI, Cloud, Productivity, Computing, Gaming & Apps",
            ogDescription: "Explore Microsoft products and services and support for your home or business. Shop Microsoft 365, Copilot, Teams, Xbox, Windows, Azure, Surface and more.",
            ogImage: "",
            twitterCard: "summary",
            viewport: "width=device-width, initial-scale=1, shrink-to-fit=no",
            charset: "UTF-8",
        },
        headings: { h1: 1, h2: 18, h3: 8, h4: 0, h5: 0, h6: 0, h1Texts: ["Get the ultimate college bundle"] },
        links: { broken: 0, internal: 88, external: 44, total: 132 },
        images: { total: 29, missingAlt: 6, withAlt: 23 },
        _id: "69faf23859140a797168cd5d",
        userId: "69dcf7cacc98f8daf29ecca3",
        url: "https://microsoft.com/",
        overallScore: 75,
        loadTime: 4929,
        pageSize: 454183,
        wordCount: 650,
        status: "completed",
        createdAt: "2026-05-06T07:48:09.000Z",
        updatedAt: "2026-05-06T07:49:09.170Z",
    },
    {
        categories: { seo: 91, performance: 100, accessibility: 90, bestPractices: 90 },
        metaData: {
            title: "Full Stack Web Development Projects with source code - GreatStack",
            description: "Project based learning platform for web developers. Find Full Stack Project, Courses, Tutorial for Next JS, MERN Stack, React JS and HTML-CSS.",
            canonical: "https://greatstack.dev/",
            robots: "",
            ogTitle: "Full Stack Web Development Projects with source code - GreatStack",
            ogDescription: "Project based learning platform for web developers. Find Full Stack Project, Courses, Tutorial for Next JS, MERN Stack, React JS and HTML-CSS.",
            ogImage: "https://greatstack.dev/greatstack_logo.jpg",
            twitterCard: "summary",
            viewport: "width=device-width, initial-scale=1",
            charset: "utf-8",
        },
        headings: { h1: 1, h2: 34, h3: 0, h4: 0, h5: 0, h6: 0, h1Texts: ["Web Development Projects"] },
        links: { broken: 0, internal: 55, external: 4, total: 60 },
        images: { total: 61, missingAlt: 16, withAlt: 45 },
        _id: "69fad6f73b51176579cd75a9",
        userId: "69dcf7cacc98f8daf29ecca3",
        url: "https://greatstack.dev/",
        overallScore: 93,
        loadTime: 2210,
        pageSize: 126438,
        wordCount: 349,
        status: "completed",
        createdAt: "2026-05-06T05:51:51.274Z",
        updatedAt: "2026-05-06T05:53:15.019Z",
    },
    {
        categories: { seo: 86, performance: 93, accessibility: 83, bestPractices: 100 },
        metaData: {
            title: "Vercel: Build and deploy the best web experiences with the AI Cloud",
            description: "Vercel gives developers the frameworks, workflows, and infrastructure to build a faster, more personalized web.",
            canonical: "https://vercel.com/",
            robots: "index, max-image-preview:large",
            ogTitle: "Vercel: Build and deploy the best web experiences with the AI Cloud – Vercel",
            ogDescription: "Vercel gives developers the frameworks, workflows, and infrastructure to build a faster, more personalized web.",
            ogImage: "https://assets.vercel.com/image/upload/contentful/image/e5382hct74si/4JmubmYDJnFtstwHbaZPev/0c3576832aae5b1a4d98c8c9f98863c3/Vercel_Home_OG.png",
            twitterCard: "summary_large_image",
            viewport: "width=device-width, initial-scale=1, maximum-scale=1",
            charset: "utf-8",
        },
        headings: { h1: 2, h2: 18, h3: 7, h4: 0, h5: 9, h6: 0, h1Texts: ["Build and deploy on the AI Cloud.", "Build and deploy on the AI Cloud."] },
        links: { broken: 0, internal: 114, external: 18, total: 132 },
        images: { total: 49, missingAlt: 7, withAlt: 42 },
        _id: "69e0b571d1621b9576e47c2a",
        userId: "69dcf7cacc98f8daf29ecca3",
        url: "https://vercel.com/",
        overallScore: 91,
        loadTime: 2797,
        pageSize: 921750,
        wordCount: 775,
        status: "completed",
        createdAt: "2026-04-16T10:09:53.689Z",
        updatedAt: "2026-04-16T10:11:05.444Z",
    },
    {
        categories: { seo: 63, performance: 100, accessibility: 100, bestPractices: 100 },
        metaData: {
            title: "Tailwind CSS UI Components & Templates - PrebuiltUI",
            description: "Tailwind CSS UI components and templates for modern web development. Get access to free, responsive and modern Tailwind CSS components to speed up your web development.",
            canonical: "https://prebuiltui.com/",
            robots: "",
            ogTitle: "PrebuiltUI - Free Tailwind CSS Components & UI Templates",
            ogDescription: "Get access to free, responsive and modern Tailwind CSS components to speed up your web development process.",
            ogImage: "https://prebuiltui.com/opengraph-image.png?opengraph-image.09u6fxlvvs1rv.png",
            twitterCard: "summary_large_image",
            viewport: "width=device-width, initial-scale=1",
            charset: "utf-8",
        },
        headings: { h1: 1, h2: 11, h3: 7, h4: 6, h5: 0, h6: 0, h1Texts: ["Explore the Ultimate  Collection of UI Components"] },
        links: { broken: 0, internal: 397, external: 6, total: 403 },
        images: { total: 124, missingAlt: 0, withAlt: 124 },
        _id: "69ddf15f1ec6a4dc0025f4bc",
        userId: "69dcf7cacc98f8daf29ecca3",
        url: "https://prebuiltui.com/",
        overallScore: 91,
        loadTime: 2022,
        pageSize: 263904,
        wordCount: 1097,
        status: "completed",
        createdAt: "2026-04-14T07:48:47.541Z",
        updatedAt: "2026-04-14T07:49:35.291Z",
    },
];
 
export const dummyWebsiteAnalysis = {
    categories: { seo: 91, performance: 100, accessibility: 90, bestPractices: 90 },
    metaData: {
        title: "Full Stack Web Development Projects with source code - GreatStack",
        description: "Project based learning platform for web developers. Find Full Stack Project, Courses, Tutorial for Next JS, MERN Stack, React JS and HTML-CSS.",
        canonical: "https://greatstack.dev/",
        robots: "",
        ogTitle: "Full Stack Web Development Projects with source code - GreatStack",
        ogDescription: "Project based learning platform for web developers. Find Full Stack Project, Courses, Tutorial for Next JS, MERN Stack, React JS and HTML-CSS.",
        ogImage: "https://greatstack.dev/greatstack_logo.jpg",
        twitterCard: "summary",
        viewport: "width=device-width, initial-scale=1",
        charset: "utf-8",
    },
    headings: { h1: 1, h2: 34, h3: 0, h4: 0, h5: 0, h6: 0, h1Texts: ["Web Development Projects"] },
    links: { broken: 0, internal: 55, external: 4, total: 60 },
    images: { total: 61, missingAlt: 16, withAlt: 45 },
    _id: "69fad6f73b51176579cd75a9",
    userId: "69dcf7cacc98f8daf29ecca3",
    url: "https://greatstack.dev/",
    overallScore: 93,
    loadTime: 2210,
    pageSize: 126438,
    wordCount: 349,
    status: "completed",
    keywords: [
        { word: "full stack", count: 28, density: 8.02, _id: "69fad74b3b51176579cd75aa" },
        { word: "projects", count: 19, density: 5.44, _id: "69fad74b3b51176579cd75ab" },
        { word: "react js", count: 12, density: 3.44, _id: "69fad74b3b51176579cd75ac" },
        { word: "mern stack", count: 9, density: 2.58, _id: "69fad74b3b51176579cd75ad" },
        { word: "ai", count: 8, density: 2.29, _id: "69fad74b3b51176579cd75ae" },
        { word: "e-commerce", count: 6, density: 1.72, _id: "69fad74b3b51176579cd75af" },
        { word: "next js", count: 5, density: 1.43, _id: "69fad74b3b51176579cd75b0" },
        { word: "saas", count: 5, density: 1.43, _id: "69fad74b3b51176579cd75b1" },
        { word: "pern stack", count: 4, density: 1.15, _id: "69fad74b3b51176579cd75b2" },
        { word: "blog", count: 3, density: 0.86, _id: "69fad74b3b51176579cd75b3" },
    ],
    issues: [
        {
            severity: "medium",
            category: "Accessibility",
            message: "16 images are missing alt text, which harms accessibility and SEO image indexing.",
            recommendation: "Add descriptive alt text to all 16 images to improve accessibility for screen readers and search engine understanding of image content.",
        },
        {
            severity: "medium",
            category: "SEO",
            message: "The page title tag is 65 characters long, which is slightly above the recommended 50-60 character limit.",
            recommendation: "Consider shortening the title tag to ensure it displays fully in search results and maintains optimal click-through rates.",
        },
        {
            severity: "medium",
            category: "SEO",
            message: "The meta description is 142 characters, slightly below the optimal range of 150-160 characters.",
            recommendation: "Expand the meta description slightly to utilize the full character limit, providing more detail and potentially improving click-through rates.",
        },
        {
            severity: "medium",
            category: "Best Practices",
            message: "The page uses one H1 and 34 H2s, but lacks H3-H6 headings, indicating a flat heading structure.",
            recommendation: "Refine the heading structure to create a clearer hierarchy (H1 > H2 > H3, etc.) for better content organization and semantic SEO.",
        },
        {
            severity: "low",
            category: "SEO",
            message: "The page does not explicitly define a robots meta tag.",
            recommendation: 'While the default behavior is index, follow, consider adding an explicit robots meta tag (<meta name="robots" content="index, follow">) for clarity and control.',
        },
        {
            severity: "low",
            category: "SEO",
            message: "While key terms are present, core phrases like 'web development' could have higher density to match user search intent more closely.",
            recommendation: "Naturally integrate 'web development' and related terms into the main content to slightly increase their density and relevance.",
        },
        {
            severity: "low",
            category: "SEO",
            message: "The page contains only 4 external links, which is relatively low.",
            recommendation: "Consider adding more high-quality, relevant external links to authoritative sources to provide additional value to users and signal credibility to search engines.",
        },
    ],
    createdAt: "2026-05-06T05:51:51.274Z",
    updatedAt: "2026-05-06T05:53:15.019Z",
};
 
export const dummyRankings = [
    {
        _id: "69faedb159140a797168cd5c",
        userId: "69dcf7cacc98f8daf29ecca3",
        keyword: "full stack projects",
        url: "https://greatstack.dev",
        domain: "greatstack.dev",
        currentPosition: 9,
        currentPage: 2,
        bestPosition: 9,
        positionChange: 3,
        active: true,
        lastChecked: "2026-05-06T07:30:52.744Z",
        status: "completed",
        competitors: [
            { position: 1, url: "https://www.reddit.com/r/FullStack/comments/1rw24f7/the_projects_that_will_get_you_hired_as_a_full/", domain: "reddit.com", title: "The projects that will get you hired as a Full Stack Web Dev ...", snippet: "Try building something that shows decision-making: authentication with edge cases, role-based access, background jobs, rate limiting, proper ...Read more" },
            { position: 2, url: "https://github.com/ZOUHAIRFGRA/100-Project-Ideas-for-Full-Stack-Developers", domain: "github.com", title: "ZOUHAIRFGRA/100-Project-Ideas-for-Full-Stack-Developers", snippet: "" },
            { position: 3, url: "https://www.geeksforgeeks.org/blogs/best-full-stack-project-ideas/", domain: "geeksforgeeks.org", title: "12 Best Full Stack Project Ideas in 2025", snippet: "" },
            { position: 4, url: "https://www.frontendmentor.io/articles/full-stack-project-ideas", domain: "frontendmentor.io", title: "12 Full-Stack Project Ideas for Your Portfolio", snippet: "" },
            { position: 5, url: "https://www.turing.com/blog/full-stack-project-ideas-for-software-developers", domain: "turing.com", title: "Twelve Full Stack Project Ideas for 2025", snippet: "" },
        ],
        createdAt: "2026-05-06T07:28:49.108Z",
        updatedAt: "2026-05-06T07:30:52.745Z",
    },
];
 
export const dummyWebsiteRanking = {
    _id: "69dd0cbd0fa79fd71e3b0473",
    userId: "69dcf7cacc98f8daf29ecca3",
    keyword: "greatstack",
    url: "https://greatstack.dev",
    domain: "greatstack.dev",
    currentPosition: 2,
    currentPage: 1,
    bestPosition: 2,
    positionChange: 0,
    active: true,
    lastChecked: "2026-05-06T09:04:47.211Z",
    status: "completed",
    rankHistory: [
        { date: "2026-05-04T18:30:00.000Z", position: 9, page: 2, title: "GreatStack: Full Stack Web Development Projects with source ...", snippet: "Project based learning platform for web developers." },
        { date: "2026-05-05T18:30:00.000Z", position: 8, page: 2, title: "GreatStack: Full Stack Web Development Projects with source ...", snippet: "Project based learning platform for web developers." },
        { date: "2026-05-06T18:30:00.000Z", position: 5, page: 2, title: "GreatStack: Full Stack Web Development Projects with source ...", snippet: "Project based learning platform for web developers." },
        { date: "2026-05-07T18:30:00.000Z", position: 1, page: 2, title: "GreatStack: Full Stack Web Development Projects with source ...", snippet: "Project based learning platform for web developers." },
        { date: "2026-05-08T18:30:00.000Z", position: 8, page: 1, title: "GreatStack: Full Stack Web Development Projects with source ...", snippet: "Project based learning platform for web developers." },
        { date: "2026-05-09T18:30:00.000Z", position: 6, page: 1, title: "GreatStack: Full Stack Web Development Projects with source ...", snippet: "Project based learning platform for web developers." },
        { date: "2026-05-10T18:30:00.000Z", position: 2, page: 1, title: "GreatStack: Full Stack Web Development Projects with source ...", snippet: "Project based learning platform for web developers." },
    ],
    competitors: [
        { position: 1, url: "https://www.youtube.com/@GreatStackDev", domain: "youtube.com", title: "GreatStack", snippet: "Build placement ready or Job ready project using React JS, MongoDB, Express and Node JS." },
        { position: 3, url: "https://github.com/greatstackdev", domain: "github.com", title: "GreatStack", snippet: "" },
        { position: 5, url: "https://www.udemy.com/user/avinash-kumar-202/", domain: "udemy.com", title: "GreatStack by Avinash | Web Development & Digital ...", snippet: "" },
        { position: 6, url: "https://www.youtube.com/channel/UCkjoHfkLEy7ZT4bA2myJ8xA/videos", domain: "youtube.com", title: "GreatStack", snippet: "" },
        { position: 9, url: "https://in.linkedin.com/company/greatstack", domain: "in.linkedin.com", title: "GreatStack", snippet: "" },
    ],
    createdAt: "2026-04-13T15:33:17.509Z",
    updatedAt: "2026-05-06T09:04:47.214Z",
};